services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app_network

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    depends_on:
      - minio
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: us-east-1
      MLFLOW_ARTIFACTS_EXTRA_PACKAGES: boto3
    command: >
      mlflow server --host 0.0.0.0 --port 5000
      --backend-store-uri postgresql://neondb_owner:npg_ZyDj34mdtqLu@ep-crimson-glitter-ac9d92fb-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
      --serve-artifacts --artifacts-destination s3://mlflow/

  fastapi:
    build: ./fastapi
    container_name: fastapi-inmet
    ports:
      - "8000:8000"
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "inmet-raw"
    depends_on:
      - minio
    volumes:
      - ./data:/data:ro
    networks:
      - app_network

  postgres:
    restart: always
    container_name: postgres
    image: "postgres:17-alpine"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - app_network
  thingsboard:
    restart: always
    image: "thingsboard/tb-node:4.2.1"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      TB_SERVICE_ID: tb-ce-node
      TB_QUEUE_TYPE: in-memory
  
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app_network

  trendz:
    restart: always
    image: "thingsboard/trendz:1.14.0"
    container_name: trendz
    depends_on:
      - postgres
      - thingsboard
    ports:
      - "8888:8888"
    environment:
      TB_API_URL: http://thingsboard:8080

      # LICENÇA – trocar pelo secret obtido no site do Trendz (trial)
      TRENDZ_LICENSE_SECRET: qE6qu96aIaszIcjbJK7ytWuf
      TRENDZ_LICENSE_INSTANCE_DATA_FILE: /data/license.data

      # Conexão com o Postgres (DB "trendz" você cria via psql)
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trendz
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      # NOVO: chave de assinatura JWT – copiar do ThingsBoard (System Admin → Security)
      JWT_TOKEN_SIGNING_KEY: dHNyQzZ6aDVLWjJpeWdCUXZNN0tMWmtraVpJb3ZidGc0ejFCUGtoUlFkNW5uV2hqWU4wd000b3kyWWRCUTRvSA
    volumes:
      - trendz-data:/data
    
    networks:
      - app_network
  
volumes:
  minio_data:
  postgresdata:
    name: tb-postgres-data
    driver: local
  trendz-data:
    driver: local

networks:
  app_network:
    driver: bridge